### ISSUE TITLE
FLOSS license

### ISSUE THREAD

**Issue by fpesari** [davidhealey/ardour-scripts#1]
Hello David,

I know you are well acquainted with FLOSS because of your other work. What about releasing these scripts under a FLOSS license (preferably the same as Ardour, GPLv2 or later, but a compatible license would also be fine), so they can be merged into Ardour and/or distributed by distro packagers? I would gladly make an openSUSE package for these, for example. Thank you!

**Comment by davidhealey** [comment]
They're all MIT licensed

**Comment by fpesari** [comment]
I see, you put the license into the individual scripts' metadata. Could you please add a COPYING or LICENSE file to make life easier for us packagers? Thank you!

**Comment by davidhealey** [comment]
I always like to include the license in the individual files. If I remember correctly this is specifically suggested in the GNU GPL documentation so that if the file becomes separated from a COPYING file the license information isn't lost. But yes I'll add a COPYING file to the repo later today.

**Comment by fpesari** [comment]
> I always like to include the license in the individual files. If I remember correctly this is specifically suggested in the GNU GPL documentation so that if the file becomes separated from a COPYING file the license information isn't lost. But yes I'll add a COPYING file to the repo later today.

Yes, you are correct, even if this practice is not always followed. The approach I use nowadays is a couple of comments with SPDX metadata, which is standardized and can be automatically read by some tools.

But having both is better, especially because us packagers sometimes take the COPYING or LICENSE file and put it into a directory on the user's machine (on openSUSE it's in `/usr/share/licenses/<packagename>`). Thank you, by the way, please close this issue when you are done :smiley:

**Comment by davidhealey** [comment]
Done :)
